# S3 configuration
s3_data_handler:
  s3_uri: "s3://occupancy-dataset/bev-dairy-more-navigable/"
  base_dir: "data"       # Base directory for downloads and S3 destination
  required_keys:
    - "left.jpg"
    - "right.jpg"
    - "seg-mask-mono.png"
    - "seg-mask-rgb.png"
  n_train: 2200          # Training sample count for GT dataset
  n_test: 400            # Test sample count for GT dataset

# Output directories
model_data_handler:
  base_dir: "data"       # Base directory for GT-train/GT-test and model dataset folders
  labels_to_remove: [0]  # List of labels to remove when cleaning masks

