# S3 configuration
s3_uri: "s3://occupancy-dataset/bev-dairy-more-navigable/"


# model dataset 
n_train: 1950 # number of training samples
n_test: 400 # number of test samples

# Directory paths
aws_dir: "data/GT-aws"  # local directory to store aws data

# Required files in each GT folder
keys:
  - "left.jpg"
  - "right.jpg"
  - "seg-mask-mono.png"
  - "seg-mask-rgb.png"

# Output directories
output_dirs:
  gt_train: "data/GT-train"
  gt_test: "data/GT-test"
  model_dataset: "data/model-dataset" 