# S3 configuration
s3_uri: "s3://occupancy-dataset/bev-dairy-more-navigable/dairy/ghdairy/2024_02_19/svo_files/front_2024-02-21-11-10-38.svo/2084_to_2226/"
s3_dest_dir: "leaf-eval"

# model dataset 
n_train: 0 # number of training samples

# assign all samples in s3_uri (leaf-folders) to test set
n_test: -1 

root_dir: "leaf-eval"

# Directory paths
aws_dir: "leaf-eval/GT-aws"  # local directory to store aws data

# Required files in each GT folder
keys:
  - "left.jpg"
  - "right.jpg"
  - "seg-mask-mono.png"
  - "seg-mask-rgb.png"

# Output directories
output_dirs:
  gt_train: "leaf-eval/GT-train"
  gt_test: "leaf-eval/GT-test"
  model_dataset: "leaf-eval/model-dataset"



  # image dimensions
image_w: 640
image_h: 480
max_disp: 64

# segmentation and heatmap parameters
n_classes_seg: 14
n_hmap: 256

# depth range (in meters)
xmin: 2.0
xmax: 7.0

# horizontal range (in meters)
ymin: -2.0
ymax: 3.0

# camera parameters
cx: 964.989
cy: 569.276
f: 1093.2768
tx: 0.12
camera_ext_x: 0.0
camera_ext_y: 0.0

# additional parameters for SBEVNet
do_ipm_rgb: false
do_ipm_feats: false
fixed_cam_confs: true

# training parameters
batch_size: 4
num_epochs: 200
learning_rate: 0.0001

# dataset parameters
json_path: 'leaf-eval/model-dataset/dataset.json'
color_map: 'configs/Mavis.yaml'
do_mask: false
do_top_seg: true
zero_mask: false

# evaluation specific parameters
checkpoint_path: 'checkpoints/best_val_model.pth'
# checkpoint_path: 'checkpoints/best_train_model.pth'
batch_size: 1
do_top_seg: false
predictions_dir: 'leaf-eval/predictions'
gpu_id: 3