# image dimensions
image_w: 640
image_h: 480
max_disp: 64

# segmentation and heatmap parameters
n_classes_seg: 14
n_hmap: 256

# depth range (in meters)
xmin: 2.0
xmax: 7.0

# horizontal range (in meters)
ymin: -2.0
ymax: 3.0

# camera parameters
cx: 964.989
cy: 569.276
f: 1093.2768
tx: 0.12
camera_ext_x: 0.0
camera_ext_y: 0.0

# additional parameters for SBEVNet
do_ipm_rgb: false
do_ipm_feats: false

# is camera confs fixed?
fixed_cam_confs: false

# training parameters
batch_size: 4
num_epochs: 200
learning_rate: 0.0001
num_workers: 4
num_gpus: 3

# dataset parameters
do_mask: false
do_top_seg: true
zero_mask: false

# paths
dataset_path: "data/model-dataset/dataset.json"
save_dir: "checkpoints"

# training configuration
# focal_loss_class_weights: [0, 0.4, 0.01, 0.1, 0, 0.8, 0.1, 0, 0, 0, 0.8, 0.2, 0, 0.2]
# cross_entropy_class_weights: [0, 0.1, 0.05, 0.1, 0, 0.1, 0.1, 0, 0, 0, 0.1, 0.1, 0, 0.1]
class_weights: [0, 0.1, 0.05, 0.1, 0, 0.1, 0.1, 0, 0, 0, 0.1, 0.1, 0, 0.1]

early_stopping_patience: 20

# loss configuration
loss_type: focal         # set to "focal" to use FocalLoss, or "cross_entropy" for the default
focal_gamma: 2.0         # gamma parameter for FocalLoss

# seed
random_seed: 420