# image dimensions
image_w: 640
image_h: 480
max_disp: 64

# segmentation and heatmap parameters
n_classes_seg: 6
n_hmap: 400

# depth range (in meters)
xmin: 0
xmax: 10

# horizontal range (in meters)
ymin: -5
ymax: 5

# camera parameters
cx: 964.989
cy: 569.276
f: 1093.2768
tx: 0.13
camera_ext_x: 0.0
camera_ext_y: 0.0

# additional parameters for SBEVNet
do_ipm_rgb: false
do_ipm_feats: false
fixed_cam_confs: true

# training parameters
batch_size: 2
num_epochs: 100
learning_rate: 0.0001

# dataset parameters
do_mask: false
do_top_seg: true
zero_mask: false
